// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class CreatureModel
{
	public int metadataId = -1;

	public int horrorProb;
	public int horrorDmg;

	public int attackType;
	public float attackProb;
	public int attackDmg;

	public int satisfactionMax;
	//
	//

	public int satisfactionDownProb;
	public int satisfactionDown;

	public int favorSkillId;
	public int favorSkillBonus;
	public int rejectSkillId;
	public int rejectSKillBonus;


	public int type = 1;
	public float var1 = 10f;
	public float var1_max = 20f;
	public float var1_warn = 5f;

	public float var2 = 10f;
	public float var2_max = 20f;
	public float var2_warn = 5f;

	public CreatureModel ()
	{
	}

	public CreatureModel clone()
	{
		CreatureModel output = new CreatureModel();

		output.metadataId = metadataId;
		output.type = type;
		output.var1 = var1;
		output.var1_max = var1_max;
		output.var1_warn = var1_warn;
		output.var2 = var2;
		output.var2_max = var2_max;
		output.var2_warn = var2_warn;

		return output;
	}
}

